export const femaleOutfits = [
  {
    slug: "default",
    label: "Default",
    categories: ["tech", "law", "finance", "med", "hospitality", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Keep subject's original outfit",
    thumbnail: "/female-outfits/default.jpg",
    prompt: "Subject wearing their original clothing unchanged from submitted reference images.",
  },

  // FORMAL BUSINESS - Law & Finance Focus
  {
    slug: "executive_suit",
    label: "Executive Suit",
    categories: ["law", "finance", "insurance", "all"],
    description: "Tailored suit with structured blazer and blouse",
    thumbnail: "/female-outfits/executive-suit.jpg",
    prompt: "Subject wearing tailored blazer in charcoal, navy, or black over crisp blouse with structured collar or elegant neckline. Natural fabric texture showing authentic suit material, realistic lapel structure, proper shoulder fit and professional tailoring, visible blouse detail at neckline.",
  },
  {
    slug: "power_suit",
    label: "Power Suit",
    categories: ["finance", "law", "all"],
    description: "Bold professional suit in jewel tones or pinstripe",
    thumbnail: "/female-outfits/power-suit.jpg",
    prompt: "Subject wearing bold professional suit in navy, charcoal, or subtle pinstripe with structured shoulders and strong silhouette, paired with silk blouse. Premium fabric texture, confident professional styling, natural lapel structure, powerful executive presence.",
  },
  {
    slug: "lawyer_formal",
    label: "Attorney Professional",
    categories: ["law", "all"],
    description: "Conservative court-appropriate attire",
    thumbnail: "/female-outfits/lawyer.jpg",
    prompt: "Subject wearing conservative blazer in black, navy, or charcoal over tailored blouse with professional neckline. Traditional business styling appropriate for courtroom, authentic fabric textures, structured shoulders, authoritative professional appearance.",
  },
  {
    slug: "finance_professional",
    label: "Finance Professional",
    categories: ["finance", "insurance", "all"],
    description: "Polished suit with silk blouse",
    thumbnail: "/female-outfits/finance.jpg",
    prompt: "Subject wearing tailored suit jacket in neutral professional color over silk or satin blouse with elegant neckline such as bow tie or jewel neck. Premium fabric with natural sheen on blouse, structured blazer with quality tailoring, sophisticated financial sector styling.",
  },
  {
    slug: "sheath_dress_formal",
    label: "Executive Sheath Dress",
    categories: ["law", "finance", "insurance", "all"],
    description: "Tailored sheath dress for formal business",
    thumbnail: "/female-outfits/sheath-formal.jpg",
    prompt: "Subject wearing tailored sheath dress in solid professional color (navy, black, charcoal, burgundy) with boat neck, jewel neck, or modest V-neck. Natural fabric drape showing quality material, realistic structured fit with clean professional lines, minimal elegant jewelry.",
  },
  {
    slug: "blazer_shell_formal",
    label: "Formal Blazer & Shell",
    categories: ["law", "finance", "insurance", "all"],
    description: "Structured blazer over elegant shell",
    thumbnail: "/female-outfits/blazer-shell.jpg",
    prompt: "Subject wearing structured blazer over sleeveless silk or satin shell with professional neckline. Premium fabric contrast between blazer and shell, authentic layering at chest, realistic shoulder structure, polished business styling.",
  },

  // BUSINESS CASUAL - Multi-Industry
  {
    slug: "business_blazer",
    label: "Business Casual Blazer",
    categories: ["tech", "law", "finance", "med", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Structured blazer with professional blouse",
    thumbnail: "/female-outfits/business-blazer.jpg",
    prompt: "Subject wearing structured blazer in neutral tone over blouse with open collar, pussy bow, or elegant neckline. Authentic fabric textures, realistic blazer shoulder structure and lapel detail, approachable professional appearance.",
  },
  {
    slug: "smart_casual_blazer",
    label: "Smart Casual Blazer",
    categories: ["tech", "med", "hospitality", "real-estate", "sales-marketing", "all"],
    description: "Unstructured blazer with casual top",
    thumbnail: "/female-outfits/smart-casual.jpg",
    prompt: "Subject wearing unstructured or soft blazer in neutral or muted tone over knit top, fitted t-shirt, or relaxed blouse. Natural fabric textures with soft shoulder drape, contemporary casual-professional fit, approachable styling.",
  },
  {
    slug: "blouse_professional",
    label: "Professional Blouse",
    categories: ["tech", "finance", "med", "hospitality", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Tailored blouse without jacket",
    thumbnail: "/female-outfits/blouse.jpg",
    prompt: "Subject wearing tailored blouse in solid color or subtle pattern with structured collar, mandarin collar, or V-neck. Natural fabric texture in silk, cotton, or quality blend, realistic button detail or neckline construction, polished professional appearance.",
  },
  {
    slug: "twin_set",
    label: "Twin Set",
    categories: ["tech", "med", "insurance", "all"],
    description: "Coordinated cardigan and shell",
    thumbnail: "/female-outfits/twinset.jpg",
    prompt: "Subject wearing coordinated cardigan over matching shell or camisole in complementary colors. Visible knit texture, authentic button detail, natural fabric layering at neckline, classic professional styling with minimal jewelry.",
  },

  // TECH INDUSTRY - Modern & Creative
  {
    slug: "tech_modern_blazer",
    label: "Modern Tech Professional",
    categories: ["tech", "sales-marketing", "all"],
    description: "Contemporary blazer with clean lines",
    thumbnail: "/female-outfits/tech-modern.jpg",
    prompt: "Subject wearing contemporary blazer with clean lines over modern blouse or quality top in coordinated colors. Authentic fabrics with modern cut, natural shoulder structure, Silicon Valley professional aesthetic with refined details.",
  },
  {
    slug: "creative_professional",
    label: "Creative Professional",
    categories: ["tech", "sales-marketing", "all"],
    description: "Blazer over premium t-shirt or casual top",
    thumbnail: "/female-outfits/creative.jpg",
    prompt: "Subject wearing tailored blazer over quality crew neck or V-neck t-shirt in solid color. Contemporary casual-professional look, authentic fabric contrast between structured blazer and soft t-shirt, natural shoulder fit, startup-friendly styling.",
  },
  {
    slug: "minimalist_modern",
    label: "Minimalist Modern",
    categories: ["tech", "sales-marketing", "all"],
    description: "Sleek monochromatic look",
    thumbnail: "/female-outfits/minimalist.jpg",
    prompt: "Subject wearing sleek monochromatic top, dress, or blazer in single neutral or bold color with clean lines. Subtle fabric texture, authentic material properties, contemporary minimalist aesthetic with precise fit.",
  },
  {
    slug: "turtleneck_professional",
    label: "Tech Turtleneck",
    categories: ["tech", "all"],
    description: "Fine-knit turtleneck for modern professional",
    thumbnail: "/female-outfits/turtleneck.jpg",
    prompt: "Subject wearing fine-gauge turtleneck in solid neutral or jewel tone with optional blazer. Authentic knit texture, natural turtleneck drape, contemporary professional styling inspired by tech industry, minimal jewelry.",
  },
  {
    slug: "wrap_style",
    label: "Wrap Style Professional",
    categories: ["tech", "hospitality", "real-estate", "sales-marketing", "all"],
    description: "Wrap dress or wrap-style top",
    thumbnail: "/female-outfits/wrap.jpg",
    prompt: "Subject wearing wrap dress or wrap-style top with V-neckline and crossover detail. Authentic fabric drape showing natural wrap construction, flattering professional fit, quality material texture, approachable modern styling.",
  },
  {
    slug: "statement_blouse",
    label: "Statement Blouse",
    categories: ["tech", "hospitality", "sales-marketing", "all"],
    description: "Blouse with interesting neckline detail",
    thumbnail: "/female-outfits/statement.jpg",
    prompt: "Subject wearing blouse with distinctive professional neckline such as ruffle collar, pleated front, or architectural detail in solid color or subtle print. Authentic fabric texture, natural drape, contemporary professional styling with personality.",
  },
  {
    slug: "tech_casual_chic",
    label: "Tech Casual Chic",
    categories: ["tech", "sales-marketing", "all"],
    description: "Elevated casual for startup environments",
    thumbnail: "/female-outfits/tech-casual.jpg",
    prompt: "Subject wearing quality knit top, fitted blouse, or modern sweater in solid or subtle pattern. Contemporary casual professional styling, authentic fabric textures, comfortable yet polished appearance for tech workplace.",
  },

  // REAL ESTATE PROFESSIONALS
  {
    slug: "realtor_professional",
    label: "Realtor Professional",
    categories: ["real-estate", "all"],
    description: "Approachable blazer for real estate agents",
    thumbnail: "/female-outfits/realtor.jpg",
    prompt: "Subject wearing approachable blazer in neutral or warm tone over blouse or shell with friendly professional styling. Polished yet accessible appearance, authentic fabric textures, real estate agent look that balances professionalism with warmth.",
  },
  {
    slug: "real_estate_blouse",
    label: "Real Estate Blouse",
    categories: ["real-estate", "all"],
    description: "Professional blouse for showings",
    thumbnail: "/female-outfits/realtor-blouse.jpg",
    prompt: "Subject wearing quality blouse in welcoming colors (soft blues, warm neutrals) with elegant neckline. Fresh approachable appearance, authentic fabric textures, real estate professional styling suitable for open houses and client meetings.",
  },
  {
    slug: "luxury_realtor",
    label: "Luxury Realtor",
    categories: ["real-estate", "all"],
    description: "Sophisticated attire for high-end properties",
    thumbnail: "/female-outfits/luxury-realtor.jpg",
    prompt: "Subject wearing premium blazer or elegant dress in sophisticated colors with refined styling. Polished upscale appearance, quality fabric textures, luxury real estate agent look conveying expertise in high-end markets.",
  },
  {
    slug: "broker_professional",
    label: "Broker Professional",
    categories: ["real-estate", "all"],
    description: "Executive attire for real estate brokers",
    thumbnail: "/female-outfits/broker.jpg",
    prompt: "Subject wearing tailored suit or premium blazer with elegant blouse or dress in professional colors. Authoritative yet approachable appearance, quality fabrics, real estate leadership styling suitable for broker or team leader roles.",
  },
  {
    slug: "property_manager",
    label: "Property Manager",
    categories: ["real-estate", "all"],
    description: "Practical professional for property management",
    thumbnail: "/female-outfits/property-manager.jpg",
    prompt: "Subject wearing business casual blazer, cardigan, or professional top suitable for active property management. Practical approachable styling, natural fabrics, property manager look for client meetings and site visits.",
  },
  {
    slug: "real_estate_dress",
    label: "Real Estate Dress",
    categories: ["real-estate", "all"],
    description: "Professional dress for realtors",
    thumbnail: "/female-outfits/realtor-dress.jpg",
    prompt: "Subject wearing professional sheath or shift dress in approachable colors with modest neckline. Polished friendly appearance, natural fabric drape, real estate professional styling that's both professional and welcoming.",
  },
  {
    slug: "realtor_summer",
    label: "Realtor Summer",
    categories: ["real-estate", "all"],
    description: "Light professional attire for warm weather",
    thumbnail: "/female-outfits/realtor-summer.jpg",
    prompt: "Subject wearing light breathable blouse or dress in fresh colors with professional styling. Summer-appropriate fabric textures, polished approachable appearance, real estate agent look suitable for warm weather showings.",
  },

  // INSURANCE PROFESSIONALS
  {
    slug: "insurance_professional",
    label: "Insurance Professional",
    categories: ["insurance", "all"],
    description: "Trustworthy business attire",
    thumbnail: "/female-outfits/insurance.jpg",
    prompt: "Subject wearing blazer and blouse or professional dress in conservative colors conveying trust and expertise. Professional authoritative appearance, natural fabric textures, insurance agent styling that balances approachability with credibility.",
  },
  {
    slug: "insurance_blazer",
    label: "Insurance Blazer Professional",
    categories: ["insurance", "all"],
    description: "Structured blazer for client meetings",
    thumbnail: "/female-outfits/insurance-blazer.jpg",
    prompt: "Subject wearing structured blazer over elegant blouse or shell in professional colors. Trustworthy polished appearance, authentic fabrics, insurance professional styling suitable for consultations and presentations.",
  },
  {
    slug: "financial_advisor_female",
    label: "Financial Advisor",
    categories: ["insurance", "finance", "all"],
    description: "Professional attire for financial services",
    thumbnail: "/female-outfits/advisor.jpg",
    prompt: "Subject wearing tailored suit, blazer combination, or professional dress conveying financial expertise. Polished trustworthy appearance, quality fabrics, financial advisor styling suitable for client meetings.",
  },
  {
    slug: "insurance_business_casual",
    label: "Insurance Business Casual",
    categories: ["insurance", "all"],
    description: "Approachable professional for agents",
    thumbnail: "/female-outfits/insurance-casual.jpg",
    prompt: "Subject wearing cardigan and blouse, sweater set, or professional dress in welcoming colors. Approachable trustworthy appearance, authentic textures, insurance professional styling that's accessible yet credible.",
  },
  {
    slug: "benefits_consultant",
    label: "Benefits Consultant",
    categories: ["insurance", "all"],
    description: "Professional for HR benefits roles",
    thumbnail: "/female-outfits/benefits.jpg",
    prompt: "Subject wearing business professional blazer, cardigan, or dress in approachable colors. Knowledgeable friendly appearance, natural fabrics, benefits consultant styling suitable for corporate presentations.",
  },
  {
    slug: "insurance_elegant",
    label: "Insurance Elegant Professional",
    categories: ["insurance", "all"],
    description: "Refined attire for senior agents",
    thumbnail: "/female-outfits/insurance-elegant.jpg",
    prompt: "Subject wearing elegant blazer, professional dress, or coordinated separates in sophisticated colors. Refined authoritative appearance, quality fabrics, senior insurance professional styling conveying experience and expertise.",
  },

  // SALES & MARKETING PROFESSIONALS
  {
    slug: "sales_professional",
    label: "Sales Professional",
    categories: ["sales-marketing", "all"],
    description: "Confident attire for sales roles",
    thumbnail: "/female-outfits/sales.jpg",
    prompt: "Subject wearing modern blazer over blouse or professional dress with confident styling. Engaging approachable appearance, authentic fabrics, sales professional look that conveys competence and likeability.",
  },
  {
    slug: "account_executive",
    label: "Account Executive",
    categories: ["sales-marketing", "all"],
    description: "Polished attire for B2B sales",
    thumbnail: "/female-outfits/account-exec.jpg",
    prompt: "Subject wearing contemporary blazer and elegant blouse or sophisticated dress. Sharp professional appearance, modern tailoring, account executive styling suitable for client presentations and negotiations.",
  },
  {
    slug: "marketing_professional",
    label: "Marketing Professional",
    categories: ["sales-marketing", "all"],
    description: "Creative professional for marketing",
    thumbnail: "/female-outfits/marketing.jpg",
    prompt: "Subject wearing contemporary blazer, creative top, or modern dress with creative professional styling. Confident stylish appearance, authentic fabrics, marketing professional look balancing professionalism with creative industry aesthetics.",
  },
  {
    slug: "sales_casual_professional",
    label: "Sales Casual Professional",
    categories: ["sales-marketing", "all"],
    description: "Approachable business casual for sales",
    thumbnail: "/female-outfits/sales-casual.jpg",
    prompt: "Subject wearing quality blouse, cardigan set, or casual dress with approachable professional styling. Friendly confident appearance, natural textures, sales professional look for relationship-building roles.",
  },
  {
    slug: "business_development",
    label: "Business Development",
    categories: ["sales-marketing", "all"],
    description: "Executive sales attire",
    thumbnail: "/female-outfits/biz-dev.jpg",
    prompt: "Subject wearing tailored blazer, sophisticated dress, or elegant separates in professional colors. Executive confident appearance, quality tailoring, business development styling suitable for enterprise partnerships.",
  },
  {
    slug: "marketing_creative",
    label: "Marketing Creative",
    categories: ["sales-marketing", "all"],
    description: "Modern creative for marketing",
    thumbnail: "/female-outfits/marketing-creative.jpg",
    prompt: "Subject wearing contemporary blazer over creative top or modern dress with artistic professional styling. Stylish confident appearance, authentic fabrics, marketing professional look with strong creative industry influence.",
  },

  // MEDICAL PROFESSIONALS
  {
    slug: "medical_professional",
    label: "Medical Professional",
    categories: ["med", "all"],
    description: "Business casual for healthcare",
    thumbnail: "/female-outfits/medical.jpg",
    prompt: "Subject wearing business casual attire such as cardigan over blouse, professional sweater, or quality top in colors appropriate for healthcare environment. Clean, approachable appearance, natural fabrics, trustworthy medical professional styling.",
  },
  {
    slug: "physician_casual",
    label: "Physician Business Casual",
    categories: ["med", "all"],
    description: "Professional attire for doctors",
    thumbnail: "/female-outfits/physician.jpg",
    prompt: "Subject wearing cardigan, sweater, or professional blouse in calming professional colors (blues, soft greens, neutrals) suitable for medical practice. Approachable yet authoritative appearance, natural fabrics, healthcare professional styling.",
  },
  {
    slug: "healthcare_cardigan",
    label: "Healthcare Cardigan",
    categories: ["med", "all"],
    description: "Open cardigan for medical professionals",
    thumbnail: "/female-outfits/healthcare-cardigan.jpg",
    prompt: "Subject wearing open-front cardigan in neutral or soft color over coordinating shell or camisole. Warm approachable appearance, visible knit texture, natural layering suitable for patient-facing roles, professional medical styling.",
  },
  {
    slug: "medical_blouse",
    label: "Medical Professional Blouse",
    categories: ["med", "all"],
    description: "Professional blouse for clinical settings",
    thumbnail: "/female-outfits/medical-blouse.jpg",
    prompt: "Subject wearing professional blouse in solid colors appropriate for healthcare (blues, teals, soft colors) with clean professional neckline. Comfortable yet polished appearance, natural fabric, trustworthy clinical styling.",
  },
  {
    slug: "silk_shell_medical",
    label: "Professional Shell",
    categories: ["med", "all"],
    description: "Elegant shell for medical professionals",
    thumbnail: "/female-outfits/silk-shell.jpg",
    prompt: "Subject wearing silk or quality shell top with elegant neckline in professional healthcare colors. Natural fabric drape, polished but approachable appearance, suitable for administrative or clinical leadership roles.",
  },
  {
    slug: "medical_sweater",
    label: "Medical Sweater Professional",
    categories: ["med", "all"],
    description: "Sweater for healthcare environments",
    thumbnail: "/female-outfits/medical-sweater.jpg",
    prompt: "Subject wearing crew neck or V-neck sweater in solid professional color over collared shirt or alone. Warm approachable appearance with authentic knit texture, natural fit, professional medical styling that balances authority with warmth.",
  },
  {
    slug: "clinical_professional",
    label: "Clinical Professional",
    categories: ["med", "all"],
    description: "Polished attire for clinic environments",
    thumbnail: "/female-outfits/clinical.jpg",
    prompt: "Subject wearing professional blouse, cardigan set, or quality top in clean professional colors suitable for clinical settings. Polished appearance with natural fabrics, approachable trustworthy styling for patient-facing roles.",
  },

  // HOSPITALITY & SERVICE
  {
    slug: "hospitality_professional",
    label: "Hospitality Professional",
    categories: ["hospitality", "all"],
    description: "Elegant attire for hotel and service",
    thumbnail: "/female-outfits/hospitality.jpg",
    prompt: "Subject wearing professional blouse, blazer, or dress in welcoming colors with polished styling. Clean sophisticated appearance, natural fabrics, hospitality styling that balances professionalism with warmth.",
  },
  {
    slug: "hotel_manager",
    label: "Hotel Manager",
    categories: ["hospitality", "all"],
    description: "Management attire for hospitality",
    thumbnail: "/female-outfits/hotel-manager.jpg",
    prompt: "Subject wearing blazer over blouse or elegant dress in professional colors. Polished approachable appearance, authentic fabrics, management-appropriate hospitality styling with refined details.",
  },
  {
    slug: "restaurant_professional",
    label: "Restaurant Professional",
    categories: ["hospitality", "all"],
    description: "Elegant attire for dining management",
    thumbnail: "/female-outfits/restaurant.jpg",
    prompt: "Subject wearing elegant blouse, dress, or blazer combination in sophisticated colors suitable for upscale dining. Refined appearance with natural fabrics, professional restaurant management styling.",
  },
  {
    slug: "jewel_tone_hospitality",
    label: "Jewel Tone Professional",
    categories: ["hospitality", "all"],
    description: "Rich colored attire for service industry",
    thumbnail: "/female-outfits/jewel-tone.jpg",
    prompt: "Subject wearing blouse or dress in jewel tone (emerald, sapphire, ruby, amethyst) with professional neckline. Natural fabric texture showing quality material, realistic color depth, welcoming hospitality styling with elegant details.",
  },
  {
    slug: "event_coordinator",
    label: "Event Coordinator",
    categories: ["hospitality", "all"],
    description: "Professional attire for event management",
    thumbnail: "/female-outfits/event.jpg",
    prompt: "Subject wearing polished blazer, dress, or coordinated separates in professional colors. Sophisticated energetic appearance suitable for event management, natural fabrics with contemporary styling.",
  },
  {
    slug: "service_elegant",
    label: "Service Professional",
    categories: ["hospitality", "all"],
    description: "Polished attire for service roles",
    thumbnail: "/female-outfits/service.jpg",
    prompt: "Subject wearing professional blouse, shell, or quality top in welcoming colors with clean styling. Approachable polished appearance, natural fabrics, professional service industry styling.",
  },
  {
    slug: "peplum_hospitality",
    label: "Peplum Professional",
    categories: ["hospitality", "all"],
    description: "Fitted top with peplum detail",
    thumbnail: "/female-outfits/peplum.jpg",
    prompt: "Subject wearing fitted blouse or top with subtle peplum detail at waist, professional neckline. Feminine professional styling with authentic fabric texture, natural construction detail, polished hospitality appearance.",
  },

  // VERSATILE CROSS-INDUSTRY OPTIONS
  {
    slug: "navy_blazer_classic",
    label: "Classic Navy Blazer",
    categories: ["tech", "law", "finance", "med", "hospitality", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Timeless navy blazer combination",
    thumbnail: "/female-outfits/navy-blazer.jpg",
    prompt: "Subject wearing classic navy blazer over white, light blue, or neutral blouse with professional neckline. Timeless styling, natural fabric textures, structured shoulders, versatile business appearance suitable for multiple professional contexts.",
  },
  {
    slug: "crew_neck_sweater",
    label: "Crew Neck Sweater",
    categories: ["tech", "med", "insurance", "all"],
    description: "Classic professional sweater",
    thumbnail: "/female-outfits/sweater.jpg",
    prompt: "Subject wearing crew neck sweater in quality knit, solid color or subtle pattern. Visible knit texture, authentic material properties, natural fit with contemporary styling, optional simple jewelry.",
  },
  {
    slug: "v_neck_layered",
    label: "Layered V-Neck",
    categories: ["tech", "med", "insurance", "all"],
    description: "V-neck sweater over collared shirt",
    thumbnail: "/female-outfits/v-neck-layered.jpg",
    prompt: "Subject wearing V-neck sweater over collared shirt with collar points visible at neckline. Authentic knit texture, natural fabric layering, preppy professional styling with realistic color coordination.",
  },
  {
    slug: "sheath_dress_versatile",
    label: "Professional Sheath Dress",
    categories: ["tech", "finance", "hospitality", "real-estate", "sales-marketing", "all"],
    description: "Versatile sheath dress",
    thumbnail: "/female-outfits/sheath.jpg",
    prompt: "Subject wearing sheath dress in solid professional color with modest neckline (jewel, boat, or V-neck). Natural fabric drape, authentic material texture, clean professional silhouette suitable for various business contexts.",
  },
  {
    slug: "silk_blouse_versatile",
    label: "Silk Blouse",
    categories: ["tech", "finance", "hospitality", "real-estate", "sales-marketing", "all"],
    description: "Elegant silk blouse",
    thumbnail: "/female-outfits/silk-blouse.jpg",
    prompt: "Subject wearing silk or satin blouse in solid color or subtle print with elegant neckline. Natural fabric sheen and drape, authentic silk texture, realistic neckline construction, refined professional styling.",
  },
  {
    slug: "cowl_neck_elegant",
    label: "Cowl Neck Elegant",
    categories: ["tech", "finance", "hospitality", "sales-marketing", "all"],
    description: "Elegant cowl neckline",
    thumbnail: "/female-outfits/cowl.jpg",
    prompt: "Subject wearing top or dress with elegant cowl neckline creating soft draped detail. Natural fabric drape showing authentic cowl construction, quality texture in silk, jersey, or crepe, sophisticated professional styling.",
  },
  {
    slug: "fitted_dress_shirt",
    label: "Fitted Dress Shirt",
    categories: ["tech", "finance", "real-estate", "all"],
    description: "Tailored button-down",
    thumbnail: "/female-outfits/dress-shirt.jpg",
    prompt: "Subject wearing fitted dress shirt with structured collar and button placket. Natural cotton texture, authentic collar and button detail, tailored professional fit at shoulders and chest.",
  },
  {
    slug: "sleeveless_shell",
    label: "Sleeveless Professional Shell",
    categories: ["tech", "hospitality", "real-estate", "sales-marketing", "all"],
    description: "Elegant sleeveless shell",
    thumbnail: "/female-outfits/shell.jpg",
    prompt: "Subject wearing sleeveless shell in solid professional color with boat neck, jewel neck, or modest scoop neck. Natural fabric drape, authentic material texture, realistic armhole construction, suitable for warm weather or layering.",
  },
  {
    slug: "summer_professional",
    label: "Summer Professional",
    categories: ["tech", "hospitality", "real-estate", "all"],
    description: "Light fabrics for warm weather",
    thumbnail: "/female-outfits/summer.jpg",
    prompt: "Subject wearing breathable linen blend or cotton top in light professional colors with elegant neckline. Authentic summer fabric texture with natural drape, fresh professional appearance, suitable for warm weather business settings.",
  },
  {
    slug: "blazer_dress",
    label: "Blazer Dress",
    categories: ["tech", "finance", "sales-marketing", "all"],
    description: "Blazer-style dress",
    thumbnail: "/female-outfits/blazer-dress.jpg",
    prompt: "Subject wearing blazer-style dress with structured shoulders and lapels. Authentic suiting fabric texture, realistic blazer construction details, contemporary tailored fit with professional dress styling.",
  },
  {
    slug: "printed_blouse_professional",
    label: "Professional Printed Blouse",
    categories: ["tech", "hospitality", "sales-marketing", "all"],
    description: "Subtle pattern blouse",
    thumbnail: "/female-outfits/printed.jpg",
    prompt: "Subject wearing blouse with subtle professional print (small florals, geometric, abstract) with structured neckline. Realistic pattern scale, authentic fabric texture, natural color coordination, professional styling with personality.",
  },
];