export const outfits = [
  {
    name: "executive_suit",
    label: "Executive Suit",
    category: "Formal",
    description: "Tailored blazer with blouse and professional styling",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing impeccably tailored blazer in charcoal, navy, or black over crisp blouse with structured collar or elegant neckline. Natural fabric texture showing authentic weave in suit material, realistic lapel structure, genuine shoulder fit with proper tailoring, visible blouse detail at neckline. Frame includes upper chest to top of head with professional headroom.",
  },
  {
    name: "business_blazer",
    label: "Business Blazer",
    category: "Formal",
    description: "Structured blazer with silk blouse",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing structured blazer in neutral tone over silk or satin blouse with bow tie, pussy bow, or open collar. Authentic fabric textures with natural material sheen on blouse, realistic blazer shoulder structure and lapel detail, subtle color coordination. Frame captures upper torso showing sophisticated professional styling with appropriate headroom.",
  },
  {
    name: "sheath_dress_formal",
    label: "Formal Sheath Dress",
    category: "Formal",
    description: "Tailored sheath dress with professional neckline",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing tailored sheath dress in solid professional color with boat neck, jewel neck, or subtle V-neck. Natural fabric drape at shoulders, authentic material texture showing quality weave, realistic fit with clean lines. Minimal jewelry at neckline or ears. Composition shows upper chest and shoulders with polished corporate styling.",
  },
  {
    name: "smart_casual_blazer",
    label: "Smart Casual Blazer",
    category: "Business Casual",
    description: "Unstructured blazer with casual top",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing unstructured or soft blazer in neutral or muted tone over casual knit top, fitted t-shirt, or relaxed blouse. Authentic fabric textures with natural shoulder drape, realistic collar or neckline detail, contemporary casual-professional fit. Frame includes upper torso with approachable business-casual presence.",
  },
  {
    name: "twin_set",
    label: "Twin Set",
    category: "Business Casual",
    description: "Cardigan over matching shell top",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing coordinated cardigan over matching shell or camisole in complementary colors. Visible knit texture, authentic button detail, natural fabric layering at neckline, realistic shoulder fit. Minimal jewelry. Composition captures upper chest showing classic professional styling with soft feminine aesthetic.",
  },
  {
    name: "blouse_professional",
    label: "Professional Blouse",
    category: "Business Casual",
    description: "Tailored blouse with elegant neckline",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing tailored blouse in solid color or subtle pattern with structured collar, mandarin collar, or elegant V-neck. Natural fabric texture showing authentic silk, cotton, or polyester blend, realistic button placket or neckline detail, proper shoulder fit. Frame shows upper torso with refined professional appearance.",
  },
  {
    name: "wrap_style",
    label: "Wrap Style",
    category: "Professional",
    description: "Wrap dress or wrap-style top",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing wrap dress or wrap-style top with V-neckline and crossover detail at chest. Authentic fabric drape showing natural wrap construction, realistic neckline structure, flattering shoulder fit with quality material texture. Minimal accessories. Composition includes upper chest showing elegant wrap styling.",
  },
  {
    name: "turtleneck_professional",
    label: "Professional Turtleneck",
    category: "Professional",
    description: "Fine-knit turtleneck",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing fine-gauge turtleneck sweater in solid neutral or jewel tone. Authentic knit texture showing natural material weight, realistic turtleneck drape at neck, proper shoulder fit with contemporary silhouette. Optional delicate necklace. Frame captures upper torso with sophisticated minimalist styling.",
  },
  {
    name: "statement_blouse",
    label: "Statement Blouse",
    category: "Creative",
    description: "Blouse with interesting neckline or detail",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing blouse with distinctive neckline detail such as ruffle collar, pleated front, or architectural neckline in solid color or subtle print. Natural fabric texture, authentic detail construction, realistic drape and fit at shoulders. Frame shows upper chest with creative professional styling and contemporary aesthetic.",
  },
  {
    name: "shell_blazer_combo",
    label: "Shell and Blazer",
    category: "Professional",
    description: "Sleeveless shell under tailored blazer",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing sleeveless shell or camisole under tailored blazer with lapels visible, creating clean layered look. Authentic fabric textures showing difference between shell and blazer materials, realistic shoulder structure, natural color coordination. Minimal jewelry at neckline. Composition captures upper torso with polished professional presence.",
  },
  {
    name: "crew_neck_sweater",
    label: "Crew Neck Sweater",
    category: "Business Casual",
    description: "Classic crew neck pullover",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing classic crew neck sweater in merino wool or cashmere blend, solid color or subtle pattern. Visible knit texture, authentic wool or cotton material properties, realistic neckline ribbing, natural shoulder fit. Optional simple necklace or earrings. Frame includes upper chest with approachable professional styling.",
  },
  {
    name: "v_neck_layered",
    label: "Layered V-Neck",
    category: "Business Casual",
    description: "V-neck sweater over collared shirt",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing V-neck sweater over collared shirt with collar points visible, creating preppy professional look. Authentic knit texture in sweater, natural fabric layering at neckline, realistic color coordination between layers. Composition shows upper torso with classic layered styling and proportional fit.",
  },
  {
    name: "silk_shell",
    label: "Silk Shell",
    category: "Professional",
    description: "Elegant silk or satin shell top",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing silk or satin shell top with elegant neckline such as scoop neck, boat neck, or subtle cowl. Natural fabric sheen, authentic silk drape at shoulders, realistic neckline construction, quality material texture. Delicate jewelry at neckline or ears. Frame captures upper chest with sophisticated feminine professional aesthetic.",
  },
  {
    name: "blazer_dress",
    label: "Blazer Dress",
    category: "Formal",
    description: "Blazer-style dress with structured shoulders",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing blazer-style dress with structured shoulders, lapels, and professional neckline. Authentic suiting fabric texture, realistic blazer construction at shoulders and chest, natural tailored fit with contemporary styling. Optional minimal jewelry. Composition shows upper torso with powerful professional presence.",
  },
  {
    name: "peplum_top",
    label: "Peplum Top",
    category: "Professional",
    description: "Fitted top with peplum detail",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing fitted top with subtle peplum detail at natural waist, professional neckline such as boat neck or jewel neck. Natural fabric texture, authentic construction detail, realistic shoulder and upper bodice fit. Minimal accessories. Frame includes upper chest showing contemporary feminine professional styling.",
  },
  {
    name: "cardigan_professional",
    label: "Open Cardigan",
    category: "Business Casual",
    description: "Open-front cardigan over shell",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing open-front cardigan in neutral tone over coordinating shell top or camisole. Visible knit or fine-gauge texture, authentic drape showing open front, natural layering at chest with realistic color palette. Frame captures upper torso with soft approachable professional appearance.",
  },
  {
    name: "polo_shirt_feminine",
    label: "Feminine Polo",
    category: "Business Casual",
    description: "Fitted polo shirt in professional setting",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing fitted polo shirt in solid color with collar detail and button placket. Authentic pique or performance fabric texture, realistic collar structure, natural fit at shoulders with contemporary tailored silhouette. Composition shows upper chest with casual professional styling.",
  },
  {
    name: "cowl_neck",
    label: "Cowl Neck",
    category: "Professional",
    description: "Elegant cowl neck top or dress",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing top or dress with elegant cowl neckline creating soft draped detail at neck. Natural fabric drape showing authentic cowl construction, realistic material weight and flow, quality texture in silk, jersey, or crepe. Minimal jewelry. Frame includes upper chest with sophisticated draped styling.",
  },
  {
    name: "monochrome_modern",
    label: "Monochrome Modern",
    category: "Creative",
    description: "Sleek monochromatic ensemble",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing sleek monochromatic top, dress, or blazer in single color with clean lines and minimal detail. Subtle fabric texture variations, authentic material properties, precise contemporary fit at shoulders and neckline. Minimal or no jewelry. Composition shows upper torso with minimalist modern aesthetic.",
  },
  {
    name: "jewel_tone_blouse",
    label: "Jewel Tone Blouse",
    category: "Creative",
    description: "Rich colored blouse with elegant styling",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing blouse in jewel tone such as emerald, sapphire, ruby, or amethyst with professional neckline. Natural fabric texture showing quality silk or polyester blend, realistic color saturation and depth, authentic collar or neckline construction. Simple jewelry. Frame captures upper chest with vibrant professional presence.",
  },
  {
    name: "blazer_tshirt",
    label: "Blazer with T-Shirt",
    category: "Creative",
    description: "Tailored blazer over premium t-shirt",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing tailored blazer over premium crew neck or V-neck t-shirt in solid color, creating contemporary casual-professional look. Authentic fabric contrast between blazer structure and t-shirt softness, realistic layering at neckline, natural shoulder fit. Frame shows upper torso with modern creative professional styling.",
  },
  {
    name: "printed_blouse",
    label: "Printed Blouse",
    category: "Creative",
    description: "Professional blouse with subtle pattern",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing blouse with subtle professional print such as small florals, geometric pattern, or abstract design with structured neckline. Realistic pattern rendering with accurate scale, authentic fabric texture, natural color coordination. Frame includes upper chest showing creative professional styling with pattern interest.",
  },
  {
    name: "sleeveless_shell",
    label: "Sleeveless Shell",
    category: "Seasonal",
    description: "Elegant sleeveless shell for warmer weather",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing sleeveless shell in solid professional color with boat neck, jewel neck, or modest scoop neck. Natural fabric drape at shoulders and neckline, authentic material texture in silk, cotton, or blend, realistic armhole construction. Delicate necklace or earrings. Composition shows upper chest with polished warm-weather professional styling.",
  },
  {
    name: "linen_blend",
    label: "Linen Blend",
    category: "Seasonal",
    description: "Breathable linen blend for summer professional",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing linen or linen-blend blouse or top in light neutral tone with relaxed professional styling. Authentic linen texture showing natural weave and subtle wrinkle characteristic of fabric, realistic collar or neckline detail, natural drape at shoulders. Frame captures upper torso with warm-weather professional appearance.",
  },
  {
    name: "fitted_dress_shirt",
    label: "Fitted Dress Shirt",
    category: "Business Casual",
    description: "Tailored button-down shirt",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing fitted dress shirt with structured collar, button placket, and tailored fit. Natural cotton or blend texture, authentic collar structure and button detail, realistic shoulder and chest fit with professional styling. Frame shows upper torso with clean classic professional appearance.",
  }
];