export const maleOutfits = [
  {
    slug: "default",
    label: "Default",
    categories: ["tech", "law", "finance", "med", "hospitality", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Keep subject's original outfit",
    thumbnail: "/male-outfits/default.jpg",
    prompt: "Subject wearing their original clothing unchanged from submitted reference images.",
  },

  // FORMAL BUSINESS - Law & Finance Focus
  {
    slug: "traditional_suit",
    label: "Traditional Business Suit",
    categories: ["law", "finance", "insurance", "all"],
    description: "Classic navy or charcoal suit with tie",
    thumbnail: "/male-outfits/traditional-suit.jpg",
    prompt: "Subject wearing traditional navy or charcoal business suit with crisp white dress shirt, conservative silk tie in solid color or subtle pattern. Natural wool suit fabric with authentic texture, proper collar structure, traditional fit with professional appearance.",
  },
  {
    slug: "three_piece_executive",
    label: "Three-Piece Executive",
    categories: ["law", "finance", "all"],
    description: "Three-piece suit for maximum formality",
    thumbnail: "/male-outfits/three-piece.jpg",
    prompt: "Subject wearing three-piece suit in charcoal or navy with dress shirt, tie, and vest visible at jacket opening. High-quality wool fabric texture, natural tie silk, authentic vest edge detail, precise traditional tailoring with authoritative executive presence.",
  },
  {
    slug: "pinstripe_professional",
    label: "Pinstripe Professional",
    categories: ["finance", "law", "all"],
    description: "Pinstripe suit for finance professionals",
    thumbnail: "/male-outfits/pinstripe.jpg",
    prompt: "Subject wearing pinstripe suit in navy or charcoal with subtle vertical stripes, white dress shirt, and coordinating tie. Authentic pinstripe pattern with accurate scale, natural wool texture, traditional banker styling with refined details.",
  },
  {
    slug: "lawyer_formal",
    label: "Attorney Formal",
    categories: ["law", "all"],
    description: "Court-appropriate formal attire",
    thumbnail: "/male-outfits/lawyer.jpg",
    prompt: "Subject wearing conservative black, navy, or charcoal suit with white dress shirt, professional tie, and optional pocket square. Natural suit fabric, crisp shirt collar, traditional cut with authoritative courtroom-appropriate styling.",
  },
  {
    slug: "investment_banker",
    label: "Investment Banker",
    categories: ["finance", "all"],
    description: "Wall Street power suit",
    thumbnail: "/male-outfits/banker.jpg",
    prompt: "Subject wearing tailored navy or charcoal suit with French cuff dress shirt visible at wrists, silk tie with subtle luxury pattern, cufflinks. Premium fabric textures, natural shirt collar structure, polished high-finance executive styling.",
  },
  {
    slug: "conservative_formal",
    label: "Conservative Formal",
    categories: ["law", "finance", "insurance", "all"],
    description: "Traditional business formal for client meetings",
    thumbnail: "/male-outfits/conservative.jpg",
    prompt: "Subject wearing traditional dark suit (black, navy, or charcoal) with white or light blue dress shirt, conservative tie, minimal accessories. Natural fabric textures, proper proportions, classic professional appearance suitable for formal business settings.",
  },

  // BUSINESS CASUAL - Multi-Industry
  {
    slug: "business_casual_blazer",
    label: "Business Casual Blazer",
    categories: ["tech", "law", "finance", "med", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Blazer with open-collar shirt",
    thumbnail: "/male-outfits/business-casual.jpg",
    prompt: "Subject wearing tailored blazer in navy, grey, or tan over button-down shirt with open collar, no tie. Authentic fabric textures, natural blazer structure, professional yet approachable appearance.",
  },
  {
    slug: "smart_casual_professional",
    label: "Smart Casual",
    categories: ["tech", "med", "hospitality", "real-estate", "sales-marketing", "all"],
    description: "Button-down shirt, no jacket",
    thumbnail: "/male-outfits/smart-casual.jpg",
    prompt: "Subject wearing quality button-down shirt in solid color or subtle pattern with open collar, top button undone, sleeves rolled or unrolled. Natural cotton texture with authentic weave, realistic collar and shoulder structure.",
  },
  {
    slug: "sweater_over_shirt",
    label: "Sweater Professional",
    categories: ["tech", "med", "insurance", "all"],
    description: "V-neck sweater over collared shirt",
    thumbnail: "/male-outfits/sweater.jpg",
    prompt: "Subject wearing quality V-neck or crewneck sweater in neutral color over collared dress shirt with collar points visible at neckline. Authentic knit texture, natural fabric layering, professional yet approachable styling.",
  },

  // TECH INDUSTRY - Modern & Creative
  {
    slug: "tech_modern",
    label: "Modern Tech Professional",
    categories: ["tech", "sales-marketing", "all"],
    description: "Slim-fit blazer, no tie, contemporary styling",
    thumbnail: "/male-outfits/tech-modern.jpg",
    prompt: "Subject wearing slim-fit blazer in modern cut over fitted dress shirt or polo with open collar, no tie. Contemporary tailoring, authentic fabric textures, clean lines with Silicon Valley professional aesthetic.",
  },
  {
    slug: "creative_tech",
    label: "Creative Tech",
    categories: ["tech", "sales-marketing", "all"],
    description: "Blazer over quality t-shirt",
    thumbnail: "/male-outfits/creative.jpg",
    prompt: "Subject wearing fitted blazer over premium crew neck t-shirt in solid color. Authentic fabric layering showing t-shirt neckline, natural blazer lapels, contemporary startup-founder styling.",
  },
  {
    slug: "tech_casual",
    label: "Tech Casual",
    categories: ["tech", "all"],
    description: "Quarter-zip or quality hoodie",
    thumbnail: "/male-outfits/tech-casual.jpg",
    prompt: "Subject wearing quality quarter-zip pullover or fitted hoodie in solid color with collar or hood visible at neckline. Natural performance fabric or cotton fleece texture, modern athletic-influenced professional styling.",
  },
  {
    slug: "minimalist_tech",
    label: "Minimalist Modern",
    categories: ["tech", "sales-marketing", "all"],
    description: "Clean monochromatic look",
    thumbnail: "/male-outfits/minimalist.jpg",
    prompt: "Subject wearing monochromatic fitted shirt or turtleneck in neutral tone with minimal accessories. Subtle fabric texture, authentic material properties, contemporary slim fit with minimalist aesthetic.",
  },
  {
    slug: "startup_casual",
    label: "Startup Casual",
    categories: ["tech", "sales-marketing", "all"],
    description: "Casual button-down or polo",
    thumbnail: "/male-outfits/startup.jpg",
    prompt: "Subject wearing casual button-down shirt or quality polo in solid color or subtle pattern with relaxed fit. Natural fabric textures, approachable contemporary styling suitable for startup environments.",
  },
  {
    slug: "tech_executive",
    label: "Tech Executive",
    categories: ["tech", "all"],
    description: "Blazer with turtleneck",
    thumbnail: "/male-outfits/tech-exec.jpg",
    prompt: "Subject wearing fine-gauge turtleneck in black, navy, or grey under tailored blazer. Authentic knit texture, natural turtleneck drape, modern executive styling inspired by tech industry leaders.",
  },

  // REAL ESTATE PROFESSIONALS
  {
    slug: "realtor_professional",
    label: "Realtor Professional",
    categories: ["real-estate", "all"],
    description: "Approachable blazer for real estate agents",
    thumbnail: "/male-outfits/realtor.jpg",
    prompt: "Subject wearing approachable blazer in neutral tone (navy, grey, tan) over dress shirt or polo with open collar. Polished but friendly appearance, authentic fabric textures, trustworthy real estate professional styling that balances professionalism with approachability.",
  },
  {
    slug: "real_estate_smart_casual",
    label: "Real Estate Smart Casual",
    categories: ["real-estate", "all"],
    description: "Button-down for open houses and showings",
    thumbnail: "/male-outfits/realtor-casual.jpg",
    prompt: "Subject wearing quality button-down shirt in light colors or subtle pattern with open collar, optional sport coat. Fresh approachable appearance with natural fabrics, friendly professional styling suitable for property showings.",
  },
  {
    slug: "luxury_realtor",
    label: "Luxury Realtor",
    categories: ["real-estate", "all"],
    description: "Upscale attire for high-end properties",
    thumbnail: "/male-outfits/luxury-realtor.jpg",
    prompt: "Subject wearing premium blazer or sport coat over quality dress shirt in sophisticated colors. Polished upscale appearance with refined fabric textures, luxury real estate styling conveying expertise in high-end markets.",
  },
  {
    slug: "broker_professional",
    label: "Broker Professional",
    categories: ["real-estate", "all"],
    description: "Executive attire for real estate brokers",
    thumbnail: "/male-outfits/broker.jpg",
    prompt: "Subject wearing tailored suit or premium blazer with dress shirt and optional tie. Authoritative yet approachable appearance, quality fabrics, real estate leadership styling suitable for broker or team leader.",
  },
  {
    slug: "property_manager",
    label: "Property Manager",
    categories: ["real-estate", "all"],
    description: "Practical professional for property management",
    thumbnail: "/male-outfits/property-manager.jpg",
    prompt: "Subject wearing business casual blazer or quality polo with professional appearance. Practical approachable styling, natural fabrics, property management professional look suitable for client meetings and site visits.",
  },
  {
    slug: "real_estate_polo",
    label: "Real Estate Polo",
    categories: ["real-estate", "all"],
    description: "Professional polo for active agents",
    thumbnail: "/male-outfits/realtor-polo.jpg",
    prompt: "Subject wearing quality polo in solid professional color with clean appearance. Active professional styling, authentic polo texture, approachable real estate agent look suitable for showings and open houses.",
  },

  // INSURANCE PROFESSIONALS
  {
    slug: "insurance_professional",
    label: "Insurance Professional",
    categories: ["insurance", "all"],
    description: "Trustworthy business attire for agents",
    thumbnail: "/male-outfits/insurance.jpg",
    prompt: "Subject wearing suit or blazer with dress shirt and tie in conservative professional colors. Trustworthy authoritative appearance, natural fabric textures, insurance agent styling that conveys reliability and expertise.",
  },
  {
    slug: "insurance_business_casual",
    label: "Insurance Business Casual",
    categories: ["insurance", "all"],
    description: "Approachable blazer for client meetings",
    thumbnail: "/male-outfits/insurance-casual.jpg",
    prompt: "Subject wearing blazer over dress shirt or quality polo with professional appearance. Approachable yet professional styling, authentic fabrics, insurance professional look that balances trust with accessibility.",
  },
  {
    slug: "financial_advisor",
    label: "Financial Advisor",
    categories: ["insurance", "finance", "all"],
    description: "Professional attire for financial services",
    thumbnail: "/male-outfits/advisor.jpg",
    prompt: "Subject wearing tailored suit or blazer with dress shirt in professional colors conveying financial expertise. Polished trustworthy appearance, quality fabrics, financial advisor styling suitable for client consultations.",
  },
  {
    slug: "insurance_agent_formal",
    label: "Insurance Agent Formal",
    categories: ["insurance", "all"],
    description: "Formal suit for insurance professionals",
    thumbnail: "/male-outfits/insurance-formal.jpg",
    prompt: "Subject wearing traditional suit with dress shirt and tie in navy, charcoal, or grey. Conservative professional appearance, authentic suit textures, formal insurance agent styling conveying stability and trust.",
  },
  {
    slug: "benefits_consultant",
    label: "Benefits Consultant",
    categories: ["insurance", "all"],
    description: "Professional attire for HR benefits roles",
    thumbnail: "/male-outfits/benefits.jpg",
    prompt: "Subject wearing business professional blazer or suit with dress shirt in approachable professional colors. Knowledgeable trustworthy appearance, natural fabrics, benefits consultant styling suitable for corporate meetings.",
  },
  {
    slug: "insurance_casual_professional",
    label: "Insurance Casual Professional",
    categories: ["insurance", "all"],
    description: "Smart casual for approachable agents",
    thumbnail: "/male-outfits/insurance-smart.jpg",
    prompt: "Subject wearing quality dress shirt or polo with optional sweater or blazer in professional colors. Warm approachable appearance, authentic textures, accessible insurance professional styling for community-focused agents.",
  },

  // SALES & MARKETING PROFESSIONALS
  {
    slug: "sales_professional",
    label: "Sales Professional",
    categories: ["sales-marketing", "all"],
    description: "Confident attire for sales roles",
    thumbnail: "/male-outfits/sales.jpg",
    prompt: "Subject wearing blazer over dress shirt or quality polo with confident professional appearance. Engaging approachable styling, authentic fabrics, sales professional look that conveys competence and likeability.",
  },
  {
    slug: "account_executive",
    label: "Account Executive",
    categories: ["sales-marketing", "all"],
    description: "Polished attire for B2B sales",
    thumbnail: "/male-outfits/account-exec.jpg",
    prompt: "Subject wearing modern blazer over fitted dress shirt with open collar or subtle tie. Sharp professional appearance, contemporary tailoring, account executive styling suitable for client meetings and presentations.",
  },
  {
    slug: "marketing_professional",
    label: "Marketing Professional",
    categories: ["sales-marketing", "all"],
    description: "Creative professional for marketing roles",
    thumbnail: "/male-outfits/marketing.jpg",
    prompt: "Subject wearing contemporary blazer or quality knit over modern shirt or t-shirt. Creative confident styling, authentic fabrics, marketing professional look that balances professionalism with creative industry aesthetics.",
  },
  {
    slug: "sales_casual_professional",
    label: "Sales Casual Professional",
    categories: ["sales-marketing", "all"],
    description: "Approachable business casual for sales",
    thumbnail: "/male-outfits/sales-casual.jpg",
    prompt: "Subject wearing quality button-down or polo with optional blazer in approachable colors. Friendly confident appearance, natural textures, sales professional styling for relationship-building roles.",
  },
  {
    slug: "business_development",
    label: "Business Development",
    categories: ["sales-marketing", "all"],
    description: "Executive sales attire",
    thumbnail: "/male-outfits/biz-dev.jpg",
    prompt: "Subject wearing tailored blazer or suit with modern shirt in professional colors. Executive confident appearance, quality tailoring, business development styling suitable for enterprise sales and partnerships.",
  },
  {
    slug: "marketing_creative",
    label: "Marketing Creative",
    categories: ["sales-marketing", "all"],
    description: "Modern creative for marketing roles",
    thumbnail: "/male-outfits/marketing-creative.jpg",
    prompt: "Subject wearing fitted blazer over quality t-shirt or modern casual shirt. Contemporary creative styling, authentic layering, marketing professional look with creative industry influence.",
  },

  // MEDICAL PROFESSIONALS
  {
    slug: "medical_professional",
    label: "Medical Professional",
    categories: ["med", "all"],
    description: "Business casual appropriate for clinical settings",
    thumbnail: "/male-outfits/medical-pro.jpg",
    prompt: "Subject wearing business casual attire such as polo shirt or button-down in professional colors suitable for healthcare environment. Clean, approachable appearance with natural fabric textures.",
  },
  {
    slug: "physician_casual",
    label: "Physician Business Casual",
    categories: ["med", "all"],
    description: "Dress shirt or sweater for doctors",
    thumbnail: "/male-outfits/physician.jpg",
    prompt: "Subject wearing dress shirt or sweater in professional solid colors (blues, greys, earth tones) appropriate for medical practice. Clean, trustworthy appearance with natural fabrics, approachable yet authoritative styling.",
  },
  {
    slug: "healthcare_polo",
    label: "Healthcare Polo",
    categories: ["med", "hospitality", "all"],
    description: "Professional polo for service industries",
    thumbnail: "/male-outfits/healthcare-polo.jpg",
    prompt: "Subject wearing quality cotton polo shirt in professional solid color with collar visible. Authentic polo knit texture, clean appearance suitable for patient-facing roles, approachable healthcare professional styling.",
  },
  {
    slug: "medical_sweater",
    label: "Medical Sweater Professional",
    categories: ["med", "all"],
    description: "Cardigan or sweater for medical professionals",
    thumbnail: "/male-outfits/medical-sweater.jpg",
    prompt: "Subject wearing cardigan or crewneck sweater in neutral color over collared shirt. Warm, approachable appearance suitable for medical practice, authentic knit textures, professional healthcare styling.",
  },
  {
    slug: "clinical_smart_casual",
    label: "Clinical Smart Casual",
    categories: ["med", "all"],
    description: "Smart casual for clinic environments",
    thumbnail: "/male-outfits/clinical.jpg",
    prompt: "Subject wearing button-down shirt or polo in solid professional colors appropriate for clinical settings. Clean, professional appearance with natural fabrics, trustworthy and approachable medical professional styling.",
  },
  {
    slug: "medical_business",
    label: "Medical Business Professional",
    categories: ["med", "all"],
    description: "Business attire for hospital administrators",
    thumbnail: "/male-outfits/medical-business.jpg",
    prompt: "Subject wearing dress shirt and optional blazer or sweater in professional colors suitable for healthcare administration. Polished appearance, natural fabrics, authoritative yet caring medical leadership styling.",
  },

  // HOSPITALITY & SERVICE
  {
    slug: "hospitality_professional",
    label: "Hospitality Professional",
    categories: ["hospitality", "all"],
    description: "Professional attire for hotel and service industries",
    thumbnail: "/male-outfits/hospitality.jpg",
    prompt: "Subject wearing dress shirt or polo in welcoming colors with optional blazer or vest. Clean, approachable appearance with natural fabrics, professional hospitality styling that balances formality with warmth.",
  },
  {
    slug: "hotel_manager",
    label: "Hotel Manager",
    categories: ["hospitality", "all"],
    description: "Manager attire for hospitality",
    thumbnail: "/male-outfits/hotel-manager.jpg",
    prompt: "Subject wearing blazer over dress shirt or quality polo in professional colors. Polished yet approachable appearance, authentic fabrics, management-appropriate hospitality styling.",
  },
  {
    slug: "restaurant_professional",
    label: "Restaurant Professional",
    categories: ["hospitality", "all"],
    description: "Professional attire for restaurant management",
    thumbnail: "/male-outfits/restaurant.jpg",
    prompt: "Subject wearing dress shirt with optional vest or blazer in dark or neutral colors. Clean, sophisticated appearance suitable for upscale dining environments, natural fabric textures.",
  },
  {
    slug: "service_casual",
    label: "Service Professional",
    categories: ["hospitality", "all"],
    description: "Smart casual for service roles",
    thumbnail: "/male-outfits/service.jpg",
    prompt: "Subject wearing quality polo or button-down shirt in solid professional color. Clean, welcoming appearance with natural fabrics, approachable service industry styling.",
  },
  {
    slug: "hospitality_summer",
    label: "Hospitality Summer",
    categories: ["hospitality", "real-estate", "all"],
    description: "Breathable attire for warm climates",
    thumbnail: "/male-outfits/hospitality-summer.jpg",
    prompt: "Subject wearing light-colored linen or cotton shirt with optional lightweight blazer. Breathable summer fabrics, fresh appearance, professional warm-weather hospitality styling.",
  },
  {
    slug: "event_coordinator",
    label: "Event Coordinator",
    categories: ["hospitality", "all"],
    description: "Professional attire for event management",
    thumbnail: "/male-outfits/event.jpg",
    prompt: "Subject wearing smart blazer over dress shirt or polo in coordinated colors. Polished, energetic appearance suitable for event management, natural fabrics with contemporary professional styling.",
  },

  // VERSATILE CROSS-INDUSTRY OPTIONS
  {
    slug: "navy_blazer_classic",
    label: "Classic Navy Blazer",
    categories: ["tech", "law", "finance", "med", "hospitality", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Timeless navy blazer combination",
    thumbnail: "/male-outfits/navy-blazer.jpg",
    prompt: "Subject wearing classic navy blazer over light blue or white dress shirt with open collar or tie. Timeless professional styling, natural wool texture, versatile business appearance suitable for multiple professional contexts.",
  },
  {
    slug: "polo_versatile",
    label: "Professional Polo",
    categories: ["tech", "med", "hospitality", "real-estate", "sales-marketing", "all"],
    description: "Quality polo for versatile professional settings",
    thumbnail: "/male-outfits/polo.jpg",
    prompt: "Subject wearing quality cotton polo in solid professional color (navy, black, grey, burgundy) with collar detail visible. Authentic polo knit texture, clean fit, versatile professional styling.",
  },
  {
    slug: "summer_professional",
    label: "Summer Professional",
    categories: ["tech", "hospitality", "real-estate", "all"],
    description: "Light fabrics for warm weather",
    thumbnail: "/male-outfits/summer.jpg",
    prompt: "Subject wearing breathable linen or cotton shirt in light colors (white, light blue, tan) with open or buttoned collar. Authentic summer fabric texture with natural drape, fresh professional warm-weather styling.",
  },
  {
    slug: "business_shirt",
    label: "Professional Dress Shirt",
    categories: ["tech", "law", "finance", "med", "insurance", "sales-marketing", "all"],
    description: "Classic dress shirt without jacket",
    thumbnail: "/male-outfits/dress-shirt.jpg",
    prompt: "Subject wearing quality dress shirt in white, light blue, or subtle pattern with open collar or tie. Crisp cotton fabric texture, natural collar structure, traditional professional shirt styling suitable for business environments.",
  },
];