export const outfits = [
  {
    name: "formal",
    label: "Formal Business",
    category: "Formal",
    description: "Tailored suit with crisp dress shirt and tie",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing impeccably tailored charcoal or navy suit jacket with crisp white dress shirt visible at collar, silk tie with subtle pattern. Natural fabric texture showing authentic weave in suit material, realistic collar structure, genuine shoulder fit with proper tailoring, visible shirt cuff at wrist if arms partially visible. Frame includes upper chest to top of head with professional headroom.",
  },
  {
    name: "business_casual",
    label: "Business Casual",
    category: "Business Casual",
    description: "Blazer with polo or button-down, no tie",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing tailored blazer in neutral tone over premium polo shirt or button-down without tie, open collar visible. Authentic fabric textures with natural material properties, subtle color variations, realistic blazer shoulder structure and lapel detail. Frame captures upper torso showing jacket and collar with appropriate headroom.",
  },
  {
    name: "smart_casual",
    label: "Smart Casual",
    category: "Business Casual",
    description: "Open-collar shirt with quality fabric",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing casual button-down shirt in solid color or subtle pattern worn open-collar, top button undone. Natural fabric textures with authentic weave patterns in shirt material, realistic collar structure, natural shoulder drape. Composition shows upper chest and shoulders with clean professional framing.",
  },
  {
    name: "creative_professional",
    label: "Creative Professional",
    category: "Creative",
    description: "Fitted blazer over t-shirt",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing fitted blazer over crew neck t-shirt or casual button-down visible at neckline. Authentic fabric layering, natural cotton weave, realistic blazer lapel and shoulder structure with contemporary fit. Frame includes upper chest showing layered styling with appropriate headroom for creative professional aesthetic.",
  },
  {
    name: "tech_casual",
    label: "Tech Casual",
    category: "Creative",
    description: "Modern pullover or hoodie",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing premium quarter-zip pullover or fitted hoodie in solid color, collar or hood visible at neckline. Natural knit or fleece textures, authentic fabric behavior, realistic shoulder fit with modern silhouette. Composition captures upper torso with contemporary casual styling and professional framing.",
  },
  {
    name: "executive_formal",
    label: "Executive Formal",
    category: "Formal",
    description: "Three-piece suit with sophisticated details",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing bespoke three-piece suit in charcoal, navy, or subtle pinstripe, luxury dress shirt with visible collar and French cuffs if arms shown, silk tie, pocket square visible in breast pocket. High-quality fabric texture, natural sheen on tie silk, authentic vest edge visible at jacket opening, precise tailoring details with polished executive presence.",
  },
  {
    name: "modern_professional",
    label: "Modern Professional",
    category: "Professional",
    description: "Slim-fit suit without tie, open collar",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing slim-fit suit jacket in modern cut without tie, fitted dress shirt with open collar visible at neckline. Natural fabric textures showing authentic material characteristics, modern tailoring with clean lapel lines, realistic proportional fit and sophisticated color coordination. Frame captures upper chest and shoulders with contemporary professional styling.",
  },
  {
    name: "casual_chic",
    label: "Casual Chic",
    category: "Creative",
    description: "Quality knitwear with refined styling",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing quality knitwear such as cashmere sweater or merino cardigan over collared shirt visible at neckline. Visible knit patterns, authentic sweater texture, natural fabric layering showing collar detail beneath. Composition includes upper torso with refined casual styling and realistic garment proportions.",
  },
  {
    name: "business_dress",
    label: "Business Dress",
    category: "Formal",
    description: "Tailored dress or blazer ensemble",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing tailored sheath dress with professional neckline or blazer with coordinating top in solid professional colors, minimal jewelry at neckline or ears. Natural material drape at shoulders, authentic tailoring visible in upper garment structure, realistic fit and proportions with professional styling and appropriate fabric texture.",
  },
  {
    name: "smart_blazer",
    label: "Smart Blazer",
    category: "Business Casual",
    description: "Structured blazer with fitted top",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing structured blazer in navy, gray, or neutral tone over fitted top or blouse visible at neckline. Visible weave patterns in blazer fabric, natural garment structure at shoulders, authentic lapel detail with realistic proportional tailoring. Frame shows upper chest and shoulder area with quality professional appearance.",
  },
  {
    name: "polo_professional",
    label: "Polo Professional",
    category: "Business Casual",
    description: "Premium polo shirt",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing premium cotton or performance polo in solid color with collar detail visible. Authentic polo knit texture, natural collar structure and button placket, realistic fit across shoulders and chest with appropriate color depth. Composition captures upper torso showing polo styling with casual professional presence.",
  },
  {
    name: "sweater_professional",
    label: "Sweater Professional",
    category: "Professional",
    description: "Crewneck or V-neck sweater over dress shirt",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing quality crewneck or V-neck sweater over collared dress shirt with visible collar points. Authentic wool or cotton knit texture, natural fabric layering at neckline, realistic sweater drape at shoulders. Frame includes upper chest showing layered professional styling with proportional tailoring and color coordination.",
  },
  {
    name: "minimalist_modern",
    label: "Minimalist Modern",
    category: "Creative",
    description: "Monochromatic outfit with clean lines",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing monochromatic or neutral-toned fitted shirt or turtleneck, minimal accessories if any. Subtle fabric texture variations, authentic material properties, precise tailoring at shoulders and neckline with contemporary slim fit. Composition shows upper torso with sophisticated minimalist aesthetic and natural color saturation.",
  },
  {
    name: "summer_professional",
    label: "Summer Professional",
    category: "Seasonal",
    description: "Breathable linen or cotton in light colors",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing breathable linen or cotton shirt in light colors with open or buttoned collar. Authentic linen weave or cotton texture showing natural summer material drape at shoulders, realistic light color palette with proportionally accurate fit. Frame captures upper chest and shoulders with warm-weather professional styling.",
  },
  {
    name: "pattern_professional",
    label: "Pattern Professional",
    category: "Seasonal",
    description: "Checked blazer or patterned shirt",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing checked blazer or patterned dress shirt with visible collar and pattern detail at chest and shoulders. Realistic pattern rendering with accurate scale and repetition, authentic fabric textures, natural color coordination. Composition shows upper torso with sophisticated pattern styling appropriate for professional settings.",
  },
  {
    name: "layered_professional",
    label: "Layered Professional",
    category: "Professional",
    description: "Blazer over vest or cardigan with dress shirt",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing blazer over vest or cardigan with dress shirt collar visible, optional tie at neckline. Authentic fabric layering with natural thickness visible at chest opening, texture differences between garments, realistic color depth with precise proportional fit. Frame captures upper torso showing professional layered styling.",
  },
  {
    name: "turtleneck_executive",
    label: "Turtleneck Executive",
    category: "Professional",
    description: "Fine-gauge turtleneck under tailored blazer",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing fine-gauge turtleneck sweater in neutral or dark tone under tailored blazer, minimal accessories. Authentic knit texture showing natural material weight, realistic turtleneck drape at neck, proper layering visible where blazer opens at chest. Composition includes upper torso with executive styling and contemporary professional aesthetic.",
  },
  {
    name: "entrepreneurial",
    label: "Entrepreneurial Style",
    category: "Seasonal",
    description: "Blazer with premium t-shirt or open collar",
    thumbnail: "",
    text: "Professional headshot framed from shoulders up. Subject wearing well-fitted blazer with casual undertone over premium t-shirt or open-collar shirt visible at neckline. Authentic material textures, natural contemporary fit at shoulders and lapels, realistic color coordination. Frame shows upper chest and shoulders with modern business-casual styling and confident professional presence.",
  }
];