export const scenes = [
  // VERSATILE NEUTRAL BACKGROUNDS - Work for All Industries
  {
    label: "Classic Gray Studio",
    slug: "formal",
    categories: ["tech", "law", "finance", "med", "hospitality", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Timeless neutral gray studio background",
    thumbnail: "/scenes/gray-studio.png",
    prompt: "Confident professional expression with direct eye contact and genuine smile. Solid neutral gray studio background with subtle gradient. Professional studio lighting creating soft even illumination with gentle shadows adding dimension to face, subtle light reflections in eyes showing proper three-point lighting setup.",
  },
  {
    label: "Bright White Studio",
    slug: "formal_bright",
    categories: ["tech", "law", "finance", "med", "hospitality", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Clean bright white background with airy feel",
    thumbnail: "/scenes/white-studio.png",
    prompt: "Confident approachable expression with genuine smile and direct eye contact. Clean bright white studio background with airy open atmosphere. Soft flattering lighting from above minimizing shadows, creating fresh modern professional appearance with wide light reflections in eyes.",
  },
  {
    label: "Soft Cream Background",
    slug: "cream_studio",
    categories: ["tech", "law", "finance", "med", "hospitality", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Warm neutral cream for approachable portraits",
    thumbnail: "/scenes/cream-studio.png",
    prompt: "Warm genuine smile with approachable confident expression. Soft cream or off-white studio background with warm undertones. Flattering soft lighting creating gentle natural shadows, warm professional atmosphere with subtle light reflections in eyes.",
  },
  {
    label: "Dark Professional",
    slug: "dark_studio",
    categories: ["tech", "law", "finance", "insurance", "all"],
    description: "Dramatic dark background for executive presence",
    thumbnail: "/scenes/dark-studio.png",
    prompt: "Confident authoritative expression with subtle smile. Dark charcoal or black studio background creating dramatic professional contrast. Dramatic side lighting creating strong definition with rim light separation from background, sophisticated executive atmosphere with focused light reflections in eyes.",
  },
  {
    label: "Soft Blue Background",
    slug: "blue_studio",
    categories: ["tech", "finance", "med", "insurance", "all"],
    description: "Professional blue backdrop conveying trust",
    thumbnail: "/scenes/blue-studio.png",
    prompt: "Confident trustworthy expression with genuine smile. Soft blue or navy gradient studio background. Professional lighting creating clean even illumination with subtle cool tones, conveying reliability and competence with natural light reflections in eyes.",
  },

  // LAW & LEGAL SETTINGS
  {
    label: "Law Office",
    slug: "law_office",
    categories: ["law", "all"],
    description: "Traditional law office with legal books",
    thumbnail: "/scenes/law-office.png",
    prompt: "Professional authoritative expression with genuine smile conveying legal expertise. Distinguished law office with wooden bookshelves filled with legal volumes and traditional wood paneling blurred in background. Warm traditional lighting from side angle creating natural shadows, professional legal atmosphere with natural light reflections in eyes.",
  },
  {
    label: "Corporate Boardroom",
    slug: "boardroom",
    categories: ["law", "finance", "insurance", "all"],
    description: "Executive boardroom for formal portraits",
    thumbnail: "/scenes/boardroom.png",
    prompt: "Confident leadership expression with professional smile. Upscale boardroom with polished wood conference table and executive leather chairs blurred in background. Professional three-point lighting with main light from 45-degree angle, fill light reducing harsh shadows, subtle rim light for separation from background.",
  },
  {
    label: "Traditional Office",
    slug: "traditional_office",
    categories: ["law", "finance", "insurance", "all"],
    description: "Classic professional office setting",
    thumbnail: "/scenes/traditional-office.png",
    prompt: "Professional confident expression with genuine smile. Traditional professional office with wooden desk, classic furniture, and professional decor blurred in background. Warm office lighting from side creating natural shadows and depth, authoritative professional atmosphere with subtle light reflections in eyes.",
  },
  {
    label: "Courthouse Background",
    slug: "courthouse",
    categories: ["law", "all"],
    description: "Formal courthouse or government building",
    thumbnail: "/scenes/courthouse.png",
    prompt: "Professional dignified expression conveying legal authority. Formal courthouse interior with classical architectural columns and marble surfaces blurred in background. Natural architectural lighting creating formal professional atmosphere with gentle shadows, conveying gravitas and legal expertise with subtle light reflections.",
  },
  {
    label: "Executive Library",
    slug: "executive_library",
    categories: ["law", "finance", "insurance", "all"],
    description: "Prestigious library with refined atmosphere",
    thumbnail: "/scenes/library.png",
    prompt: "Thoughtful confident smile conveying intellectual expertise. Prestigious library with wooden bookshelves, leather-bound volumes, and refined furnishings blurred in background. Warm sophisticated lighting from side angle creating natural depth and shadows, elegant professional atmosphere with natural light reflections in eyes.",
  },
  {
    label: "Legal Conference Room",
    slug: "legal_conference",
    categories: ["law", "finance", "insurance", "sales-marketing", "all"],
    description: "Professional meeting room setting",
    thumbnail: "/scenes/conference.png",
    prompt: "Professional confident expression with trustworthy smile. Professional conference room with modern table, executive chairs, and subtle corporate decor blurred in background. Balanced professional lighting creating even illumination with gentle shadows, business meeting atmosphere with natural light reflections in eyes.",
  },

  // FINANCE & BUSINESS
  {
    label: "Financial District Office",
    slug: "finance_office",
    categories: ["finance", "insurance", "all"],
    description: "Prestigious financial office environment",
    thumbnail: "/scenes/finance-office.png",
    prompt: "Professional confident smile conveying financial expertise and integrity. Prestigious financial office with modern furnishings and subtle trading screens or financial aesthetic in blurred background, potential screen glow. Professional studio lighting with subtle cool tones reflecting modern finance environment, natural light reflections in eyes.",
  },
  {
    label: "City Skyline",
    slug: "city_skyline",
    categories: ["finance", "law", "tech", "real-estate", "insurance", "sales-marketing", "all"],
    description: "Urban skyline through office windows",
    thumbnail: "/scenes/skyline.png",
    prompt: "Professional confident smile conveying leadership. Urban city skyline visible through large windows in blurred background with architectural silhouettes and sky visible. Natural window light from side mixed with interior lighting creating professional depth, triangular light reflections in eyes showing window light.",
  },
  {
    label: "Banking Interior",
    slug: "banking",
    categories: ["finance", "insurance", "all"],
    description: "Sophisticated banking environment",
    thumbnail: "/scenes/banking.png",
    prompt: "Professional trustworthy expression with confident smile. Sophisticated banking interior with marble surfaces, refined furnishings, and professional corporate aesthetic blurred in background. Balanced professional lighting creating authoritative financial atmosphere with clean even illumination, subtle light reflections in eyes.",
  },
  {
    label: "Investment Office",
    slug: "investment_office",
    categories: ["finance", "insurance", "all"],
    description: "Modern investment firm setting",
    thumbnail: "/scenes/investment.png",
    prompt: "Confident professional smile conveying financial acumen. Modern investment office with sleek furnishings and subtle screens showing market data in blurred background. Professional lighting with cool undertones mixed with ambient screen glow, creating contemporary finance atmosphere with natural light reflections.",
  },
  {
    label: "Corporate Executive",
    slug: "corporate_executive",
    categories: ["finance", "law", "insurance", "sales-marketing", "all"],
    description: "High-level executive office",
    thumbnail: "/scenes/executive.png",
    prompt: "Authoritative confident expression with professional smile. High-level executive office with premium furnishings, large desk, and sophisticated corporate decor blurred in background. Professional lighting from multiple angles creating polished executive presence with balanced illumination, subtle light reflections in eyes.",
  },
  {
    label: "Business Lounge",
    slug: "business_lounge",
    categories: ["finance", "hospitality", "real-estate", "insurance", "all"],
    description: "Upscale business lounge or club",
    thumbnail: "/scenes/lounge.png",
    prompt: "Professional refined smile conveying sophistication. Upscale business lounge with leather furniture, elegant decor, and refined atmosphere blurred in background. Warm ambient lighting creating sophisticated professional environment with gentle shadows, natural light reflections in eyes.",
  },

  // MEDICAL & HEALTHCARE
  {
    label: "Medical Office",
    slug: "medical_office",
    categories: ["med", "all"],
    description: "Clean modern medical office environment",
    thumbnail: "/scenes/medical-office.png",
    prompt: "Compassionate genuine smile conveying medical expertise and trustworthiness. Clean modern medical office with clinical environment and professional medical equipment subtly visible in blurred background. Bright clean lighting creating natural clinical illumination with neutral-cool color temperature, conveying professionalism and care with gentle light reflections in eyes.",
  },
  {
    label: "Healthcare Professional",
    slug: "healthcare",
    categories: ["med", "all"],
    description: "Clinical setting with medical backdrop",
    thumbnail: "/scenes/healthcare.png",
    prompt: "Warm trustworthy smile conveying medical compassion. Healthcare facility with clean clinical surfaces, subtle medical equipment, and professional healthcare environment blurred in background. Soft flattering lighting creating approachable yet professional atmosphere with clean natural illumination, wide light reflections in eyes.",
  },
  {
    label: "Hospital Administrative",
    slug: "hospital_admin",
    categories: ["med", "all"],
    description: "Hospital office for administrators",
    thumbnail: "/scenes/hospital-admin.png",
    prompt: "Professional caring expression with confident smile. Hospital administrative office with professional desk, healthcare decor, and clean modern environment blurred in background. Balanced professional lighting creating trustworthy medical leadership atmosphere with natural illumination, subtle light reflections in eyes.",
  },
  {
    label: "Medical Clinic",
    slug: "clinic",
    categories: ["med", "all"],
    description: "Private practice clinic setting",
    thumbnail: "/scenes/clinic.png",
    prompt: "Approachable genuine smile conveying medical expertise and patient care. Private medical clinic with clean professional surfaces, subtle medical charts or equipment, and calming healthcare environment blurred in background. Soft natural lighting creating warm approachable clinical atmosphere with gentle light reflections.",
  },
  {
    label: "Wellness Center",
    slug: "wellness",
    categories: ["med", "hospitality", "all"],
    description: "Modern wellness or spa medical setting",
    thumbnail: "/scenes/wellness.png",
    prompt: "Warm caring smile conveying holistic healthcare expertise. Modern wellness center with natural elements, clean professional surfaces, and calming healthcare environment blurred in background. Soft natural lighting with warm undertones creating approachable healing atmosphere, gentle light reflections in eyes.",
  },
  {
    label: "Medical Professional Studio",
    slug: "medical_studio",
    categories: ["med", "all"],
    description: "Clean medical professional backdrop",
    thumbnail: "/scenes/medical-studio.png",
    prompt: "Trustworthy professional smile conveying medical competence. Clean light blue or soft gray clinical background suggesting medical professionalism. Clean even lighting creating professional healthcare atmosphere with neutral color temperature, conveying both expertise and approachability with natural light reflections.",
  },

  // TECH & MODERN PROFESSIONAL
  {
    label: "Modern Tech Office",
    slug: "tech_office",
    categories: ["tech", "sales-marketing", "all"],
    description: "Contemporary tech company environment",
    thumbnail: "/scenes/tech-office.png",
    prompt: "Genuine innovative smile with confident presence. Modern tech office with monitors showing subtle screen glow, sleek modern furniture, and contemporary design elements blurred in background. Soft mixed lighting combining natural window light with cool monitor glow, creating dynamic tech atmosphere with natural light reflections.",
  },
  {
    label: "Startup Space",
    slug: "startup",
    categories: ["tech", "sales-marketing", "all"],
    description: "Dynamic startup or co-working environment",
    thumbnail: "/scenes/startup.png",
    prompt: "Engaging genuine smile with entrepreneurial energy. Modern startup space with contemporary furniture, creative elements, and collaborative workspace aesthetic blurred in background. Bright natural lighting mixed with ambient workspace glow creating dynamic innovative atmosphere, wide light reflections in eyes.",
  },
  {
    label: "Creative Studio",
    slug: "creative_studio",
    categories: ["tech", "sales-marketing", "all"],
    description: "Modern creative or design studio",
    thumbnail: "/scenes/creative.png",
    prompt: "Genuine inspired smile conveying creative vision and professional confidence. Contemporary creative studio with design materials, modern workspace elements, and innovative aesthetic blurred in background. Soft natural window light mixed with studio ambient lighting creating accurate colors and creative atmosphere.",
  },
  {
    label: "Coffee Shop Professional",
    slug: "coffee_shop",
    categories: ["tech", "hospitality", "real-estate", "sales-marketing", "all"],
    description: "Modern coffee shop for approachable portraits",
    thumbnail: "/scenes/coffee.png",
    prompt: "Warm friendly smile with relaxed professional posture. Modern coffee shop with natural wood textures, café equipment, and inviting atmosphere blurred in background. Soft natural window light from side mixed with warm interior café lighting, creating approachable casual professional atmosphere with natural eye reflections.",
  },
  {
    label: "Glass Office Modern",
    slug: "glass_office",
    categories: ["tech", "finance", "sales-marketing", "all"],
    description: "Contemporary office with glass architecture",
    thumbnail: "/scenes/glass-office.png",
    prompt: "Natural confident expression with genuine professional smile. Contemporary office with glass surfaces, minimalist architecture, and modern design elements blurred in background. Light from 45-degree angle creating triangular light reflection in eyes, natural side lighting adding depth to facial features.",
  },
  {
    label: "Innovation Lab",
    slug: "innovation_lab",
    categories: ["tech", "all"],
    description: "Tech innovation or research space",
    thumbnail: "/scenes/innovation.png",
    prompt: "Confident innovative expression with genuine smile. Modern innovation lab with technology equipment, contemporary workspace design, and cutting-edge aesthetic blurred in background. Bright clean lighting with subtle cool tones creating forward-thinking technology atmosphere, natural light reflections in eyes.",
  },

  // HOSPITALITY & SERVICE
  {
    label: "Hotel Lobby",
    slug: "hotel_lobby",
    categories: ["hospitality", "all"],
    description: "Elegant hotel lobby environment",
    thumbnail: "/scenes/hotel.png",
    prompt: "Genuine warm smile conveying hospitality excellence and professional grace. Luxurious hotel lobby with sophisticated marble or wood decor, elegant furnishings, and welcoming atmosphere blurred in background. Soft flattering lighting from above with warm inviting tones creating hospitality atmosphere, wide light reflections in eyes.",
  },
  {
    label: "Restaurant Fine Dining",
    slug: "restaurant",
    categories: ["hospitality", "all"],
    description: "Upscale restaurant setting",
    thumbnail: "/scenes/restaurant.png",
    prompt: "Engaging genuine smile conveying culinary passion and hospitality expertise. Upscale restaurant with elegant refined decor, fine dining elements, and sophisticated ambiance blurred in background. Warm intimate lighting from 45-degree angle creating flattering illumination with natural shadows adding depth.",
  },
  {
    label: "Hospitality Reception",
    slug: "reception",
    categories: ["hospitality", "all"],
    description: "Professional hotel or venue reception",
    thumbnail: "/scenes/reception.png",
    prompt: "Welcoming genuine smile conveying service excellence. Professional reception area with elegant desk, refined furnishings, and hospitality decor blurred in background. Balanced warm lighting creating inviting professional atmosphere suitable for guest-facing roles, natural light reflections in eyes.",
  },
  {
    label: "Event Space",
    slug: "event_space",
    categories: ["hospitality", "sales-marketing", "all"],
    description: "Elegant event or conference venue",
    thumbnail: "/scenes/event.png",
    prompt: "Professional engaging smile conveying event management expertise. Elegant event space with sophisticated decor, ambient lighting elements, and refined venue aesthetic blurred in background. Soft flattering lighting creating polished professional hospitality atmosphere with natural shadows.",
  },
  {
    label: "Resort Setting",
    slug: "resort",
    categories: ["hospitality", "all"],
    description: "Upscale resort or spa environment",
    thumbnail: "/scenes/resort.png",
    prompt: "Warm welcoming smile conveying luxury service excellence. Upscale resort with elegant natural elements, refined decor, and sophisticated hospitality environment blurred in background. Soft natural lighting with warm undertones creating premium hospitality atmosphere, gentle light reflections in eyes.",
  },
  {
    label: "Boutique Interior",
    slug: "boutique",
    categories: ["hospitality", "real-estate", "sales-marketing", "all"],
    description: "Upscale boutique or service environment",
    thumbnail: "/scenes/boutique.png",
    prompt: "Professional refined smile conveying personalized service expertise. Upscale boutique interior with elegant displays, refined furnishings, and sophisticated retail environment blurred in background. Soft flattering lighting creating welcoming professional atmosphere with accurate color rendering.",
  },

  // REAL ESTATE SETTINGS
  {
    label: "Luxury Property Exterior",
    slug: "luxury_property",
    categories: ["real-estate", "all"],
    description: "Upscale property exterior or entrance",
    thumbnail: "/scenes/luxury-property.png",
    prompt: "Confident welcoming smile conveying real estate expertise. Luxury residential property exterior with elegant architecture, landscaping, or entrance features softly blurred in background. Natural outdoor lighting with warm undertones creating approachable professional atmosphere, natural light reflections showing outdoor environment.",
  },
  {
    label: "Modern Home Exterior",
    slug: "home_exterior",
    categories: ["real-estate", "all"],
    description: "Contemporary home or property backdrop",
    thumbnail: "/scenes/home-exterior.png",
    prompt: "Friendly professional smile with approachable confident presence. Modern residential property with contemporary architecture and landscaping softly blurred in background. Soft natural outdoor lighting creating fresh approachable real estate professional atmosphere with gentle light reflections.",
  },
  {
    label: "Real Estate Office",
    slug: "realtor_office",
    categories: ["real-estate", "all"],
    description: "Professional real estate office setting",
    thumbnail: "/scenes/realtor-office.png",
    prompt: "Warm professional smile conveying real estate expertise and trustworthiness. Modern real estate office with professional desk, property listings, and welcoming decor blurred in background. Bright natural lighting creating approachable professional atmosphere, wide light reflections in eyes.",
  },
  {
    label: "Property Showing Interior",
    slug: "property_interior",
    categories: ["real-estate", "all"],
    description: "Elegant home interior for realtors",
    thumbnail: "/scenes/property-interior.png",
    prompt: "Confident welcoming smile with approachable professional presence. Upscale home interior with modern or classic furnishings, large windows, and elegant residential features blurred in background. Natural window light mixed with interior lighting creating warm inviting real estate atmosphere.",
  },
  {
    label: "Urban Real Estate",
    slug: "urban_realtor",
    categories: ["real-estate", "all"],
    description: "City property or urban development backdrop",
    thumbnail: "/scenes/urban-realtor.png",
    prompt: "Professional confident smile conveying urban real estate expertise. Urban setting with modern buildings, city architecture, or downtown property features blurred in background. Natural outdoor lighting mixed with urban reflections creating dynamic professional real estate atmosphere.",
  },
  {
    label: "Suburban Professional",
    slug: "suburban_realtor",
    categories: ["real-estate", "all"],
    description: "Suburban neighborhood setting",
    thumbnail: "/scenes/suburban.png",
    prompt: "Warm friendly smile conveying community real estate expertise. Suburban residential setting with tree-lined streets, well-maintained homes, or neighborhood features softly blurred in background. Soft natural outdoor lighting creating approachable family-friendly real estate professional atmosphere.",
  },
  {
    label: "Real Estate Outdoor",
    slug: "realtor_outdoor",
    categories: ["real-estate", "all"],
    description: "Professional outdoor setting for agents",
    thumbnail: "/scenes/realtor-outdoor.png",
    prompt: "Confident approachable smile with professional presence. Outdoor setting with natural landscaping, or property features softly blurred in background. Golden hour or bright natural lighting creating warm welcoming real estate professional atmosphere with natural light reflections.",
  },

  // INSURANCE SETTINGS
  {
    label: "Insurance Office",
    slug: "insurance_office",
    categories: ["insurance", "all"],
    description: "Professional insurance office environment",
    thumbnail: "/scenes/insurance-office.png",
    prompt: "Trustworthy professional smile conveying insurance expertise. Professional insurance office with desk, client chairs, and welcoming corporate decor blurred in background. Balanced professional lighting creating trustworthy approachable atmosphere suitable for client consultations, natural light reflections in eyes.",
  },
  {
    label: "Financial Services Office",
    slug: "financial_services",
    categories: ["insurance", "finance", "all"],
    description: "Financial planning or advisory setting",
    thumbnail: "/scenes/financial-services.png",
    prompt: "Confident trustworthy smile conveying financial expertise. Professional financial services office with modern furnishings, subtle financial materials, and client-facing decor blurred in background. Balanced professional lighting creating credible approachable financial advisor atmosphere with natural light reflections.",
  },
  {
    label: "Insurance Conference Room",
    slug: "insurance_conference",
    categories: ["insurance", "all"],
    description: "Meeting room for insurance professionals",
    thumbnail: "/scenes/insurance-conference.png",
    prompt: "Professional confident smile conveying insurance leadership. Professional conference room with table, chairs, and corporate insurance office aesthetic blurred in background. Balanced lighting creating trustworthy professional atmosphere suitable for team leadership or client presentations.",
  },
  {
    label: "Community Insurance Office",
    slug: "community_insurance",
    categories: ["insurance", "all"],
    description: "Approachable local insurance office",
    thumbnail: "/scenes/community-insurance.png",
    prompt: "Warm approachable smile conveying community insurance expertise. Friendly professional office with welcoming decor and comfortable client area blurred in background. Soft warm lighting creating accessible trustworthy atmosphere for community-focused insurance agents.",
  },
  {
    label: "Corporate Insurance",
    slug: "corporate_insurance",
    categories: ["insurance", "all"],
    description: "Corporate insurance or benefits setting",
    thumbnail: "/scenes/corporate-insurance.png",
    prompt: "Professional authoritative smile conveying corporate insurance expertise. Modern corporate office with professional furnishings and business aesthetic blurred in background. Clean professional lighting creating credible corporate insurance professional atmosphere with natural light reflections.",
  },

  // SALES & MARKETING SETTINGS
  {
    label: "Sales Office Modern",
    slug: "sales_office",
    categories: ["sales-marketing", "all"],
    description: "Dynamic sales environment",
    thumbnail: "/scenes/sales-office.png",
    prompt: "Confident engaging smile with dynamic professional presence. Modern sales office with collaborative workspace, technology, and energetic business environment blurred in background. Bright professional lighting creating motivated sales professional atmosphere with natural light reflections.",
  },
  {
    label: "Client Meeting Space",
    slug: "client_meeting",
    categories: ["sales-marketing", "insurance", "real-estate", "all"],
    description: "Professional client meeting area",
    thumbnail: "/scenes/client-meeting.png",
    prompt: "Professional confident smile with welcoming presence. Professional meeting space with comfortable seating, modern table, and client-friendly decor blurred in background. Balanced lighting creating approachable professional sales atmosphere suitable for consultations and presentations.",
  },
  {
    label: "Marketing Agency",
    slug: "marketing_agency",
    categories: ["sales-marketing", "all"],
    description: "Creative marketing agency environment",
    thumbnail: "/scenes/marketing-agency.png",
    prompt: "Confident creative smile with professional presence. Modern marketing agency with creative workspace, design elements, and contemporary agency aesthetic blurred in background. Bright creative lighting with accurate colors creating dynamic marketing professional atmosphere.",
  },
  {
    label: "Corporate Sales",
    slug: "corporate_sales",
    categories: ["sales-marketing", "all"],
    description: "Enterprise sales or B2B setting",
    thumbnail: "/scenes/corporate-sales.png",
    prompt: "Professional executive smile conveying enterprise sales expertise. Corporate business environment with premium furnishings and professional aesthetic blurred in background. Professional lighting creating authoritative sales professional atmosphere suitable for high-level business development.",
  },
  {
    label: "Trade Show Backdrop",
    slug: "trade_show",
    categories: ["sales-marketing", "all"],
    description: "Professional exhibition or event setting",
    thumbnail: "/scenes/trade-show.png",
    prompt: "Engaging confident smile with dynamic professional presence. Professional exhibition or trade show environment with branded displays and business event aesthetic blurred in background. Bright professional lighting creating energetic sales and marketing atmosphere.",
  },

  // OUTDOOR & NATURAL LIGHT OPTIONS
  {
    label: "Natural Outdoor Professional",
    slug: "outdoor",
    categories: ["tech", "hospitality", "real-estate", "sales-marketing", "all"],
    description: "Professional outdoor natural lighting",
    thumbnail: "/scenes/outdoor.png",
    prompt: "Authentic genuine smile with confident natural expression. Outdoors with natural greenery or corporate campus architecture softly blurred in background, natural sky visible. Golden hour natural sunlight creating warm flattering illumination with soft shadows, natural rim lighting from sun, gentle light reflections in eyes showing outdoor sky.",
  },
  {
    label: "Urban Professional",
    slug: "urban",
    categories: ["tech", "finance", "real-estate", "sales-marketing", "all"],
    description: "Urban architecture or city backdrop",
    thumbnail: "/scenes/urban.png",
    prompt: "Confident professional smile with urban energy. Urban setting with modern architecture, city elements, and contemporary building surfaces blurred in background. Natural outdoor lighting mixed with urban reflections creating dynamic professional atmosphere, natural light reflections in eyes.",
  },
  {
    label: "Campus Setting",
    slug: "campus",
    categories: ["med", "tech", "insurance", "all"],
    description: "Corporate campus or professional grounds",
    thumbnail: "/scenes/campus.png",
    prompt: "Approachable professional smile with confident presence. Corporate or professional campus with modern architecture and professional buildings blurred in background. Soft natural outdoor lighting creating clean professional appearance with gentle shadows, natural light reflections showing sky.",
  },
];