export const settings = [
  {
    name: "formal",
    label: "Formal",
    category: "Studio",
    description: "Professional executive portrait with confident expression",
    thumbnail: "",
    text: "Professional executive portrait with confident expression and direct eye contact, natural genuine smile. Solid neutral studio background in dark gray or charcoal. Professional studio lighting with soft even illumination creating gentle shadows that add dimension to facial features, subtle catchlights in eyes. Shot on Canon EOS R5 with 85mm portrait lens at f/2.8 aperture, sharp focus on face with clean background separation. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 8K resolution.",
  },
  {
    name: "formal_bright",
    label: "Formal Bright",
    category: "Studio",
    description: "Bright white studio background with airy atmosphere",
    thumbnail: "",
    text: "Professional executive portrait with confident approachable expression, genuine smile, direct eye contact. Clean bright white seamless studio background with natural light falloff creating airy open atmosphere. Butterfly lighting setup with main light directly above creating flattering soft illumination, minimizing shadows, wide catchlights in eyes. Shot on Sony A7R IV with 85mm f/1.8 lens at f/4 aperture. Natural skin texture with visible pores and authentic detail, realistic not airbrushed, photorealistic high-key portrait, 8K resolution.",
  },
  {
    name: "coffeeshop",
    label: "Coffee Shop",
    category: "Hospitality",
    description: "Warm approachable portrait in modern coffee shop",
    thumbnail: "",
    text: "Warm approachable portrait in modern coffee shop with natural wood textures and cafe equipment visible in blurred background. Subject with genuinely friendly smile and relaxed professional posture. Soft natural window light from the left creates gentle loop lighting pattern with natural catchlights in eyes, mixing with warm interior ambient lighting. Shot on Nikon D850 with 85mm lens at f/2.8, shallow depth of field creating creamy background bokeh. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "office",
    label: "Modern Office",
    category: "Office",
    description: "Contemporary office with glass surfaces",
    thumbnail: "",
    text: "Professional yet personable portrait in contemporary office with glass surfaces and minimalist architecture slightly blurred in background. Natural confident expression with genuine smile and direct eye contact. Rembrandt lighting with key light at 45 degrees creating signature triangular catchlight, dramatic yet natural side lighting adding depth to facial features. Shot on Canon EOS R5 with 85mm portrait lens at f/2.8 aperture. Natural skin texture with visible pores and subtle detail, realistic not airbrushed, authentic appearance, photorealistic, 8K resolution.",
  },
  {
    name: "library",
    label: "Library",
    category: "Professional",
    description: "Intellectual portrait in elegant library setting",
    thumbnail: "",
    text: "Intellectual yet approachable portrait in elegant library with wooden bookshelves and book spines naturally blurred in background. Subject with warm knowing smile and thoughtful expression showing genuine wisdom. Soft loop lighting from 30-45 degree angle creating natural portrait lighting with gentle shadows and catchlights in eyes, warm ambient library atmosphere. Shot on Sony A7R IV with 85mm f/1.8 lens at f/2.8, natural depth of field. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "cityscape",
    label: "Urban Skyline",
    category: "Outdoor",
    description: "Urban skyline with city architecture",
    thumbnail: "",
    text: "Ambitious yet approachable portrait with urban city skyline visible through windows in blurred background, natural architectural detail and atmospheric perspective. Professional smile conveying confident leadership presence. Split lighting at 90 degrees illuminating half the face with dramatic yet professional effect, mixing cool window light with warm interior lighting. Shot on Canon EOS R5 with 85mm portrait lens at f/4 aperture. Natural skin texture with visible pores and authentic detail, realistic not airbrushed, photorealistic, 8K resolution.",
  },
  {
    name: "coworking",
    label: "Co-working Space",
    category: "Hospitality",
    description: "Vibrant co-working space with creative elements",
    thumbnail: "",
    text: "Innovative and enthusiastic portrait in vibrant co-working space with modern furniture and creative elements naturally blurred in background. Subject with engaging genuine smile and confident creative presence. Clamshell beauty lighting with light above and subtle fill below creating flattering soft light with wide catchlights in eyes, mixed with ambient workspace lighting. Shot on Nikon D850 with 85mm lens at f/2.8. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "conference",
    label: "Conference Room",
    category: "Office",
    description: "Upscale boardroom with executive setting",
    thumbnail: "",
    text: "Authoritative yet collaborative portrait in upscale boardroom with polished conference table and executive chairs slightly blurred in background. Professional smile conveying leadership and confidence. Professional three-point lighting setup with key light from camera left at 45 degrees, fill light reducing shadows, subtle rim light for separation. Shot on Canon EOS R5 with 85mm portrait lens at f/4 aperture. Natural skin texture with visible pores and authentic detail, realistic not airbrushed, photorealistic, 8K resolution.",
  },
  {
    name: "tech",
    label: "Tech Startup",
    category: "Office",
    description: "Modern tech office with monitors and sleek furniture",
    thumbnail: "",
    text: "Forward-thinking enthusiastic portrait in modern tech office with monitors showing subtle screen glow and sleek furniture naturally blurred in background. Genuine innovative smile with dynamic confident presence. Soft mixed lighting combining natural window light with cool monitor glow creating contemporary tech atmosphere, loop lighting pattern with natural catchlights reflecting screen environment. Shot on Sony A7R IV with 85mm f/1.8 lens at f/2.8. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "outdoor",
    label: "Outdoor Professional",
    category: "Outdoor",
    description: "Dynamic outdoor portrait with natural lighting",
    thumbnail: "",
    text: "Dynamic and energetic portrait outdoors with natural greenery or corporate campus architecture naturally blurred in background, genuine sky and atmospheric effects. Authentic genuine smile with confident natural posture. Golden hour natural sunlight creating warm flattering illumination with soft shadows, natural rim lighting from sun, gentle catchlights in eyes showing sky reflection. Shot on Canon EOS R5 with 85mm portrait lens at f/2.8 aperture. Natural skin texture with visible pores enhanced by natural light, authentic appearance with individual hair strands visible, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "creative",
    label: "Creative Studio",
    category: "Outdoor",
    description: "Artistic studio with design materials",
    thumbnail: "",
    text: "Creative and inspired portrait in artistic studio with design materials and gallery-style elements naturally blurred in background. Genuine inspired smile conveying artistic vision and professional confidence. Soft natural window light from left creating gentle loop lighting pattern, mixing with studio ambient lighting for accurate color rendering. Shot on Nikon D850 with 85mm lens at f/2.8 aperture, natural depth of field. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "hospitality",
    label: "Hotel Lobby",
    category: "Hospitality",
    description: "Luxurious hotel lobby with sophisticated decor",
    thumbnail: "",
    text: "Welcoming and warm portrait in luxurious hotel lobby with sophisticated marble and wood decor, elegant furnishings naturally blurred in background. Genuine warm smile conveying hospitality excellence and professional grace. Soft butterfly lighting from above creating flattering illumination with warm inviting tones, subtle shadows under nose, wide catchlights in eyes. Shot on Sony A7R IV with 85mm f/1.8 lens at f/2.8. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "medical",
    label: "Medical Office",
    category: "Professional",
    description: "Clean modern medical office with clinical environment",
    thumbnail: "",
    text: "Caring and authoritative portrait in clean modern medical office with clinical environment and professional medical equipment subtly blurred in background. Compassionate genuine smile conveying medical expertise and trustworthiness. Bright clean loop lighting creating natural portrait lighting with accurate neutral-cool color temperature, gentle catchlights in eyes, professional clinical atmosphere. Shot on Canon EOS R5 with 85mm portrait lens at f/4 aperture. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 8K resolution.",
  },
  {
    name: "academic",
    label: "University Campus",
    category: "Professional",
    description: "Distinguished university campus with collegiate architecture",
    thumbnail: "",
    text: "Scholarly yet approachable portrait on distinguished university campus with collegiate architecture and academic buildings naturally blurred in background, natural outdoor lighting. Thoughtful warm smile conveying knowledge and mentorship. Soft natural window light or outdoor lighting creating gentle Rembrandt lighting pattern with triangular catchlight, natural shadows adding dimension. Shot on Nikon D850 with 85mm lens at f/2.8 aperture. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "restaurant",
    label: "Fine Dining",
    category: "Hospitality",
    description: "Upscale restaurant with elegant refined decor",
    thumbnail: "",
    text: "Personable and passionate portrait in upscale restaurant with elegant refined decor and fine dining elements naturally blurred in background. Engaging genuine smile conveying culinary passion and hospitality. Warm intimate Rembrandt lighting at 45 degrees creating dramatic yet flattering side lighting with triangular catchlight, natural shadows adding depth and sophistication. Shot on Sony A7R IV with 85mm f/1.8 lens at f/2.8. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "finance",
    label: "Financial District",
    category: "Office",
    description: "Prestigious financial office with trading screens",
    thumbnail: "",
    text: "Sharp and trustworthy portrait in prestigious financial office with trading screens or banking aesthetic subtly visible in blurred background, potential screen glow. Professional confident smile conveying financial acumen and integrity. Professional studio lighting with subtle cool tones and potential screen color influence, loop lighting creating natural catchlights in eyes. Shot on Canon EOS R5 with 85mm portrait lens at f/4 aperture. Natural skin texture with visible pores and authentic detail, realistic not airbrushed, photorealistic, 8K resolution.",
  },
  {
    name: "law",
    label: "Law Office",
    category: "Office",
    description: "Distinguished law office with traditional wood paneling",
    thumbnail: "",
    text: "Authoritative yet approachable portrait in distinguished law office with legal books and traditional wood paneling naturally blurred in background. Professional genuine smile conveying legal expertise and trustworthiness. Warm traditional loop lighting from 30-45 degree angle creating natural portrait lighting with gentle shadows, professional legal atmosphere with natural catchlights in eyes. Shot on Nikon D850 with 85mm lens at f/2.8 aperture. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "retail",
    label: "Retail Showroom",
    category: "Hospitality",
    description: "Modern upscale retail space with premium products",
    thumbnail: "",
    text: "Customer-focused and welcoming portrait in modern upscale retail space with premium products and sophisticated merchandising naturally blurred in background. Genuine warm smile conveying sales expertise and service excellence. Bright inviting clamshell lighting creating flattering soft illumination with wide catchlights in eyes, accurate color rendering for retail environment. Shot on Sony A7R IV with 85mm f/1.8 lens at f/4 aperture. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 4K resolution.",
  },
  {
    name: "architecture",
    label: "Architecture Studio",
    category: "Office",
    description: "Contemporary architecture studio with design plans",
    thumbnail: "",
    text: "Visionary yet practical portrait in contemporary architecture studio with design plans and architectural models naturally blurred in background. Professional genuine smile conveying technical expertise and creative vision. Clean bright loop lighting creating natural portrait lighting with accurate color rendering, gentle catchlights in eyes, modern professional atmosphere. Shot on Canon EOS R5 with 85mm portrait lens at f/2.8 aperture. Natural skin texture with visible pores, authentic appearance, realistic facial proportions, photorealistic, 8K resolution.",
  }
];
